name: Update cIPacksStore.json

on:
  push:
    branches:
      - main

env:
  PACK_FOLDER: 'packFolder'
  PACKS_STORE_FILE: 'cIPacksStore.json'

jobs:
  find-directory:
    runs-on: ubuntu-latest
    outputs:
      directory: ${{ steps.find_directory.outputs.directory }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Find pushed directory
        id: find_directory
        run: |
          echo "::set-output name=directory::$(find $PACK_FOLDER -maxdepth 1 -type d -printf '%T@ %p\n' | sort -k1 -nr | cut -d" " -f2- | head -1)"
    
  zip-directory:
    needs: find-directory
    runs-on: ubuntu-latest
    outputs:
      zip-file: ${{ steps.zip_directory.outputs.zip_file }}
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Zip directory
        id: zip_directory
        run: |
          cd ${{ needs.find-directory.outputs.directory }}
          zip -r ../$PACKS_STORE_FILE.zip .
          echo "::set-output name=zip_file::$PACKS_STORE_FILE.zip"

  modify-manifest:
    needs: find-directory
    runs-on: ubuntu-latest
    env:
      MANIFEST_FILE: 'cIManifest.json'
    steps:
      - name: Check if manifest exists
        id: check_manifest
        run: |
          if [[ -f "${{ needs.find-directory.outputs.directory }}/$MANIFEST_FILE" ]]; then
            echo "::set-output name=manifest_found::true"
          else
            echo "::set-output name=manifest_found::false"
          fi

      - name: Modify cIPacksStore.json
        if: ${{ needs.modify-manifest.outputs.manifest_found == 'true' }}
        run: |
          cd $GITHUB_WORKSPACE
          jq --arg pack "$(cat ${{ needs.find-directory.outputs.directory }}/$MANIFEST_FILE)" '. += [{"name": $pack.name, "description": $pack.description, "author": $pack.pack_author, "icon_author": $pack.maker, "filename": "${{ steps.zip_directory.outputs.zip_file }}" }]' $PACKS_STORE_FILE > $PACKS_STORE_FILE.new
          mv $PACKS_STORE_FILE.new $PACKS_STORE_FILE
