name: Build and Deploy Packs

on:
  push:
    branches: [ main ]
    paths:
      - "packFolder/**"

env:
  packsStoreFile: "cIPacksStore.json"

jobs:
  build_pack:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"

      - name: Install Dependencies
        run: |
          cd packFolder
          npm install

      - name: Find pushed directory
        id: find_dir
        run: |
          echo "::set-output name=dir::$(find packFolder -type d -name 'cI.*' -printf '%T@ %p\n' | sort -n | tail -1 | cut -d' ' -f2 | xargs basename)"

      - name: Get pack data
        id: pack_data
        run: |
          echo "::set-output name=packdata::$(jq -r ".[] | select(.name == \"${{ needs.build_pack.outputs.name }}\") | {name: .name, description: .description, author: .pack_maker, icon_author: .author, filename: \"${{ needs.build_pack.outputs.name }}.cIPack\"}" ${env.packsStoreFile})"
        shell: bash

      - name: Append pack data to packs store
        id: append_data
        run: |
          packname="${{ steps.find_dir.outputs.dir }}"
          manifest_file="packFolder/$packname/cIManifest.json"
          author=$(jq -r '.pack_maker' "$manifest_file")
          icon_author=$(jq -r '.maker' "$manifest_file")
          description=$(jq -r '.description' "$manifest_file")
          pack_file="$packname.cIPack"
          new_data="{\"name\":\"$packname\",\"description\":\"$description\",\"author\":\"$author\",\"icon_author\":\"$icon_author\",\"filename\":\"$pack_file\"}"
          manifest_content=$(cat $GITHUB_WORKSPACE/cIPackStore.json|sed 's/.$//')
          echo $manifest_content
          echo "$manifest_content, $new_data]" > "$GITHUB_WORKSPACE/cIPackStore.json"
          printf "\r\n* [$packname](/packs/$pack_file)" >> "$GITHUB_WORKSPACE/README.md"
        env:
          packsStoreFile: ${{ env.packsStoreFile }}

      - name: Set up packDir environment variable
        run: echo "packDir=../packDir" >> $GITHUB_ENV

      - name: Zip and move pack folder
        working-directory: packFolder
        run: |
          zip -r "$name.cIPack" "$name" -i "*"
          mv "$name.cIPack" ../packs/
          mv "$name" "$packDir/$name"
        env:
          name: "${{ steps.find_dir.outputs.dir }}"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          token: ${{ secrets.PACKBUILDER }}