name: Pack Release

on:
  push:
    branches: [ main ]

jobs:
  find_directory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Find pushed directory
        id: find_dir
        run: |
          DIR="$(find . -type d -name '*' -maxdepth 1 -not -path '*/\.*' | head -1)"
          echo "::set-output name=dir::$DIR"

  pack_and_delete:
    needs: find_directory
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get directory path
        run: echo "Directory path: ${{ needs.find_directory.outputs.dir }}"
        id: get_dir_path

      - name: Zip pack directory
        run: |
          cd ${{ needs.find_directory.outputs.dir }}
          zip -r pack.zip . -x "pack.zip"
          echo "::set-output name=zip_file::pack.zip"

      - name: Move pack zip to packs folder
        run: mv ${{ needs.pack_and_delete.outputs.zip_file }} packs
        id: move_zip

      - name: Delete pushed directory
        run: rm -rf ${{ needs.find_directory.outputs.dir }}
  
  modify_pack_store:
    needs: pack_and_delete
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Modify cIPacksStore.json
        id: modify_pack_store
        run: |
          if [ ! -f "cIPacksStore.json" ]; then
            echo "[]"> cIPacksStore.json
          fi

          PACK_NAME=$(jq -r '.name' ${{ needs.find_manifest.outputs.manifest_file }})
          PACK_DESC=$(jq -r '.description' ${{ needs.find_manifest.outputs.manifest_file }})
          PACK_AUTHOR=$(jq -r '.pack_author' ${{ needs.find_manifest.outputs.manifest_file }})
          ICON_AUTHOR=$(jq -r '.maker' ${{ needs.find_manifest.outputs.manifest_file }})

          if ! grep -q "$PACK_NAME" cIPacksStore.json; then
            jq --arg pn "$PACK_NAME" --arg pd "$PACK_DESC" --arg pa "$PACK_AUTHOR" --arg ia "$ICON_AUTHOR" \
              '. += [{"name": $pn, "description": $pd, "author": $pa, "icon_author": $ia, "filename": $pn + ".zip"}]' \
              cIPacksStore.json > tmp && mv tmp cIPacksStore.json
          fi

      - name: Show modified cIPacksStore.json
        run: cat cIPacksStore.json
