name: Build and Deploy Packs

on:
  push:
    paths:
      - "packFolder/**"

env:
  packsStoreFile: "cIPacksStore.json"
  packDir: "packs"

jobs:
  build_and_deploy_pack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Check for pack folder changes
        id: check_for_pack_changes
        run: |
          echo "::set-output name=pack_folder_changed::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -q 'packFolder/' && echo true || echo false)"
        shell: bash
      
      - name: Build and deploy pack
        if: steps.check_for_pack_changes.outputs.pack_folder_changed == 'true'
        env:
          packDir: ${{ env.packDir }}
        run: |
          cd packFolder
          packname="$(jq -r '.name' cIManifest.json)"
          zipname="$packname.cIPack.zip"
          zip -r "$zipname" ./*
          mv "$zipname" ../${{ env.packDir }}/$packname.cIPack
          cd ..
          rm -rf packFolder
          pack_author="$(jq -r '.pack_author' packDir/$packname/cIManifest.json)"
          icon_author="$(jq -r '.maker' packDir/$packname/cIManifest.json)"
          description="$(jq -r '.description' packDir/$packname/cIManifest.json)"
          filename="$packname.cIPack"
          echo "{\"name\":\"$packname\",\"description\":\"$description\",\"author\":\"$pack_author\",\"icon_author\":\"$icon_author\",\"filename\":\"$filename\"}" >> ${{ env.packsStoreFile }}
          echo "Added pack $packname to ${{ env.packsStoreFile }}"
