name: Build and Deploy Packs

on:
  push:
    branches: [ main ]
    paths:
      - "packFolder/**"

env:
  PACKS_STORE_FILE: "cIPacksStore.json"

jobs:
  build_and_deploy_pack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"

      - name: Install Dependencies
        run: |
          cd packFolder
          npm install

      - name: Find pushed directory
        id: find_dir
        run: |
          echo "DIR=$(basename $(dirname $(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -m1 'packFolder/')))" >> $GITHUB_ENV

      - name: Get pack name
        id: pack_name
        run: |
          PACK_NAME=$(jq -r '.name' packFolder/${{ env.DIR }}/cIManifest.json)
          echo "PACK_NAME=${PACK_NAME}" >> $GITHUB_ENV

      - name: Zip and move pack folder
        run: |
          cd packFolder
          ZIP_NAME="${PACK_NAME}.cIPack"
          zip -r "${ZIP_NAME}" "${PACK_NAME}" -i
          mv "${ZIP_NAME}" ../packs/
          rm -rf "${PACK_NAME}"
          echo "PACK_FILENAME=${ZIP_NAME}" >> $GITHUB_ENV

      - name: Update packs store
        uses: gr2m/create-or-update-file@v2.6.0
        with:
          path: ${{ env.PACKS_STORE_FILE }}
          message: "Add pack ${{ env.PACK_NAME }}"
          content: |
            [
              {
                "name": "${{ env.PACK_NAME }}",
                "description": "$(jq -r '.description' packFolder/${{ env.DIR }}/cIManifest.json)",
                "author": "$(jq -r '.pack_author' packFolder/${{ env.DIR }}/cIManifest.json)",
                "icon_author": "$(jq -r '.maker' packFolder/${{ env.DIR }}/cIManifest.json)",
                "filename": "${{ env.PACK_FILENAME }}"
              }
            ]
          updater: github-actions
          update_method: replace

      - name: Move pack directory
        run: |
          mv packFolder packDir/${{ env.DIR }}
