name: Build and Deploy Packs

on:
  push:
    branches: [ main ]
    paths:
      - "packFolder/**"

env:
  packsStoreFile: "cIPacksStore.json"

jobs:
  build_pack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"

      - name: Install Dependencies
        run: |
          cd packFolder
          npm install

      - name: Find pushed directory
        id: find_dir
        run: |
          echo "::set-output name=dir::$(basename $(dirname $(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -m1 'packFolder/')))"
        shell: bash

      - name: Get pack data
        id: pack_data
        run: |
          echo "::set-output name=packdata::$(jq -r ".[] | select(.name == \"${{ needs.build_pack.outputs.name }}\") | {name: .name, description: .description, author: .pack_maker, icon_author: .author, filename: \"${{ needs.build_pack.outputs.name }}.cIPack\"}" ${env.packsStoreFile})"
        shell: bash

      - name: Zip and move pack folder
        run: |
          cd packFolder
          echo "zipname=$zipname"
          echo "packname=$packname"
          ls -R
          zip -r "$zipname" "$packname" -i "*.json"
          mv "$zipname" ../packs/
          rm -rf "$packname"
        env:
          zipname: "$packname.cIPack"
          packname: "${{ steps.find_dir.outputs.dir }}"

      - name: Append pack data to packs store
        id: append_data
        run: |
          packname="${{ steps.find_dir.outputs.dir }}"
          manifest_file="packFolder/$packname/cIManifest.json"
          pack_author=$(jq -r '.pack_author' "$manifest_file")
          icon_author=$(jq -r '.maker' "$manifest_file")
          description=$(jq -r '.description' "$manifest_file")
          pack_file="$packname.cIPack"
          new_data="{\"name\":\"$packname\",\"description\":\"$description\",\"author\":\"$pack_author\",\"icon_author\":\"$icon_author\",\"filename\":\"$pack_file\"}"
          echo "$new_data" >> "$GITHUB_WORKSPACE/$env.packsStoreFile"
        env:
          packsStoreFile: ${{ env.packsStoreFile }}

      - name: Move pack directory
        run: |
          mv packFolder "${{ env.packDir }}"

  update_packs_store:
    runs-on: ubuntu-latest
    needs: build_pack
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create or update packs store file
        uses: marvinpinto/action-automatic-releases@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILEPATH: ${{ env.packsStoreFile }}
          RELEASE_NAME: "Update packs store"
          RELEASE_BODY: "Add pack ${{ needs.build_pack.outputs.packname }}"
          TAG_NAME: "v1"
          COMMIT_MESSAGE: "Add pack ${{ needs.build_pack.outputs.packname }}"
