name: Build pack

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Find pushed directory
      id: find_pushed_dir
      run: |
        cd packFolder
        echo "::set-output name=pushed_dir::$(find . -type d -name ".git" -prune -o -print | sed -n '2 p' | cut -d'/' -f2)"

    - name: Get pack name and version from manifest
      id: get_pack_info
      run: |
        PACK_DIR="./packFolder/${{ steps.find_pushed_dir.outputs.pushed_dir }}"
        PACK_MANIFEST="${PACK_DIR}/cIManifest.json"
        echo "::set-output name=pack_name::$(jq -r '.name' "${PACK_MANIFEST}")"
        echo "::set-output name=pack_version::$(jq -r '.version' "${PACK_MANIFEST}")"

    - name: Create packs directory if it doesn't exist
      run: mkdir -p packs

    - name: Create pack zip file
      run: |
        PACK_DIR="./packFolder/${{ steps.find_pushed_dir.outputs.pushed_dir }}"
        PACK_NAME="${{ steps.get_pack_info.outputs.pack_name }}"
        PACK_VERSION="${{ steps.get_pack_info.outputs.pack_version }}"
        ZIP_NAME="cI.${PACK_NAME}-${PACK_VERSION}.zip"
        cd "${PACK_DIR}"
        zip -r "../../packs/${ZIP_NAME}" .
        cd ..
        rm -rf "${PACK_DIR}"
        echo "::set-output name=zip_file::packs/${ZIP_NAME}"

    - name: Modify cIPacksStore.json
      if: success()
      uses: Grifonas/cIManifest-to-cIPacksStore@v1
      with:
        fileName: "${{ steps.get_pack_info.outputs.pack_name }}"
        fileDescription: "${{ steps.get_pack_info.outputs.pack_description }}"
        fileAuthor: "${{ steps.get_pack_info.outputs.pack_author }}"
        fileIconAuthor: "${{ steps.get_pack_info.outputs.maker }}"
        filename: "${{ steps.get_pack_info.outputs.zip_file }}"

    - name: Commit changes
      if: success()
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add cIPacksStore.json
        git commit -m "Update cIPacksStore.json with new pack"
