name: Build and Deploy Packs

on:
  push:
    branches: [ main ]
    paths:
      - "packFolder/**"

env:
  packsStoreFile: "cIPacksStore.json"

jobs:
  build_pack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"

      - name: Install Dependencies
        run: |
          cd packFolder
          npm install

      - name: Find pushed directory
        id: find_dir
        run: |
          echo "::set-output name=dir::$(basename $(dirname $(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -m1 'packFolder/')))"
        shell: bash

      - name: Get pack name
        id: pack_name
        run: |
          echo "::set-output name=packname::$(jq -r '.name' packFolder/${{ steps.find_dir.outputs.dir }}/cIManifest.json)"
        shell: bash

      - name: Zip and move pack folder
        run: |
          cd packFolder
          zip -r "$zipname" "$packname"
          mv "$zipname" ../packs/
          rm -rf "$packname"
        env:
          zipname: "($packname).zip"
          packname: "${{ steps.find_dir.outputs.dir }}"

  update_packs_store:
    runs-on: ubuntu-latest
    needs: build_pack
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get pack data
        id: pack_data
        run: |
          echo "::set-output name=packdata::$(jq -r ".[] | select(.name == \"${{ needs.build_pack.outputs.packname }}\") | {name: .name, description: .description, author: .pack_author, icon_author: .maker, filename: \"${{ needs.build_pack.outputs.packname }}.zip\"}" ${env.packsStoreFile})"
        env:
          packsStoreFile: ${{ env.packsStoreFile }}

      - name: Update packs store
        uses: gr2m/create-or-update-file@v2.6.0
        with:
          path: ${{ env.packsStoreFile }}
          message: "Add pack ${{ needs.build_pack.outputs.packname }}"
          content: "${{ steps.pack_data.outputs.packdata }}"
          updater: github-actions
          update_method: replace
