name: PR Validation

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  validate_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check for excluded files in packFolder
        if: "!contains(github.event.head_commit.added, '.cIManifest') && !contains(github.event.head_commit.added, '.ico') && !contains(github.event.head_commit.added, '.txt') && contains(github.event.head_commit.added, 'packFolder/')"
        run: |
          echo "Invalid Pull Request! Please make sure that packFolder only contains .cIManifest, .ico, or .txt files."
          exit 0

      - name: Check for valid files in packFolder
        if: "contains(github.event.head_commit.added, 'packFolder/')"
        run: |
          echo "${{ github.event.head_commit.added }}"
          if ! [[ "$(find "${{ github.workspace }}/${{ github.event.head_commit.added }}" -type f ! -iname '*.cIManifest' ! -iname '*.ico' ! -iname '*.txt')" ]]; then
            echo "Invalid Pull Request! Please make sure that packFolder only contains .cIManifest, .ico, or .txt files."
            exit 0
          fi

      - name: Check for .cIManifest and .ico files
        if: "contains(github.event.head_commit.added, '.cIManifest') || contains(github.event.head_commit.added, '.ico')"
        run: |
          if ! [[ "$(find "${{ github.workspace }}/${{ github.event.head_commit.added }}" -type f -iname '*.cIManifest' -o -iname '*.ico')" ]]; then
            echo "Invalid Pull Request! Please make sure that the packFolder includes a .cIManifest file and/or .ico files."
            exit 0
          fi

      - name: Check if PR was closed by workflow
        id: pr_closed_by_workflow
        uses: andstor/github-action-pr-closed-by-workflow@v1.0.1
        with:
          workflow_file_name: 'pr_validation.yml'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Close invalid PR
        if: |
          !steps.pr_closed_by_workflow.outputs.result &&
          (
            github.actor == github.event.pull_request.user.login || 
            contains(github.event.pull_request.requested_reviewers.*.login, github.actor) || 
            contains(github.event.pull_request.requested_teams.*.slug, join("/", [github.repository.owner.login, github.event.pull_request.base.ref, "moderators"]))
          )
        uses: peter-evans/close-pull-request@v1
        with:
          pull_request_number: ${{ github.event.number }}
          message: "This pull request has been closed because it is invalid. Please open a new pull request with the required changes."
          keep_branch: false
